/**
 * Constants file for Hoosier Tank
 * 
 * Version    Date            Author           Remarks
 * 1.00       11 Feb 2014     nathanah
 *
 */

// NETSUITE WORKORDER STATUSES
var NETSUITE_WORKORDER_STATUS_FULLYBUILT = 'fullyBuilt';
var NETSUITE_WORKORDER_STATUS_PENDINGBUILD = 'pendingBuild';
var NETSUITE_WORKORDER_STATUS_PARTIALLYBUILT = 'partiallyBuilt';
var NETSUITE_WORKORDER_STATUS_PENDINGAPPROVAL = 'pendingApproval';
var NETSUITE_WORKORDER_STATUS_CLOSED = 'closed';

// NETSUITE WORK ORDER "ORDER STATUS"
var NETSUITE_WORKORDER_ORDERSTATUS_PLANNED = 'A';
var NETSUITE_WORKORDER_ORDERSTATUS_RELEASED = 'B';

// NETSUITE ORDER STATUS
var NETSUITE_SALESORDER_STATUS_CLOSED = 'closed';
var NETSUITE_SALESORDER_STATUS_BILLED = 'billed';

// NETSUITE ORDER FILTER STATUS
//Netsuite SO Statuses ID:
//SalesOrd:A = Pending Approval
//SalesOrd:B = Pending Fulfillment
//SalesOrd:C = Cancelled
//SalesOrd:D = Partially Fulfilled
//SalesOrd:E = Pending Billing/Partially Fulfilled
//SalesOrd:F = Pending Billing
//SalesOrd:G = Billed
//SalesOrd:H = Closed
var NETSUITE_SALESORDER_STATUS_PENDINGFULFILLMENT = 'SalesOrd:B'; //Can't use 'pendingFulfillment' here

// PRODUCTION SCHEDULE PROCESSING STATUSES
var HT_PRODUCTIONSCHEDULEPROCESSINGSTATUS_OPEN = '1';
var HT_PRODUCTIONSCHEDULEPROCESSINGSTATUS_PROCESSING = '2';

// PRODUCTION SCHEDULE STATUS
var HT_PRODUCTIONSCHEDULESTATUS_PENDINGSCHEDULING = '1';
var HT_PRODUCTIONSCHEDULESTATUS_SCHEDULED = '2';
var HT_PRODUCTIONSCHEDULESTATUS_VERIFIED = '3';

// WORK ORDER TYPES
var HT_WORKORDERTYPE_PRODUCTION = '1';
var HT_WORKORDERTYPE_PREPROCESSING = '2';
var HT_WORKORDERTYPE_DEMANDFORECAST = '3';

// FINISHED GOODS PRODUCTION STATUS
var HT_FINISHEDGOODSPRODSTATUS_OPEN = '1';
var HT_FINISHEDGOODSPRODSTATUS_VERIFIED = '2';
var HT_FINISHEDGOODSPRODSTATUS_BUILT = '3';
var HT_FINISHEDGOODSPRODSTATUS_CREATINGBUILDS = '4';
var HT_FINISHEDGOODSPRODSTATUS_ERROR = '5';
var HT_FINISHEDGOODSPRODSTATUS_DELETINGBUILDS = '6';

// FINISHED GOODS PRODUCTION SHIFT
var HT_FINISHEDGOODSPRODSHIFT_DAY = '1';
var HT_FINISHEDGOODSPRODSHIFT_NIGHT = '2';

// CHANGE ORDER STATUS
var HT_CHANGE_ORDER_STATUS_PENDING_CUSTOMER_APPROVAL = '1';
var HT_CHANGE_ORDER_STATUS_APPROVED = '2';
var HT_CHANGE_ORDER_STATUS_DENIED= '3';
var HT_CHANGE_ORDER_STATUS_COMPLETED = '4';
var HT_CHANGE_ORDER_STATUS_PENDING_PURCHASING_APPROVAL = '5';
var HT_CHANGE_ORDER_STATUS_PENDING_PRODUCTION_APPROVAL = '6';
var HT_CHANGE_ORDER_STATUS_PENDING_SHIPPING_APPROVAL = '7';

// TANK COATING EXTERIOR
var HT_TANKCOATINGEXT_GLOSS = '1';
var HT_TANKCOATINGEXT_RP = '2';
var HT_TANKCOATINGEXT_SPRAY = '3';
var HT_TANKCOATINGEXT_TEXTURE = '4';
var HT_TANKCOATINGEXT_NONE = '5';

//Hoosier Tank role Ids
var HT_ROLE_PURCHASING = '1005';
var HT_ROLE_CUSTOMER_SERVICE = '1005'; //We need to set the correct one once role is created.
var HT_ROLE_SHIPPING = '1005'; //We need to set the correct one once role is created.
var HT_ROLE_PRODUCTION = '1005'; //We need to set the correct one once role is created.
var HT_ROLE_ADMINISTRATOR = '3';

// CONTACT CATEGORIES
var HT_CONTACTCATEGORY_PURCHASINGMANAGER = '2';
var HT_CONTACTCATEGORY_BUYER = '1';
var HT_CONTACTCATEGORY_INVOICE = '6';

// LOCATIONS
var LOCATION_PRODUCTION = '1';

// HT ITEM TYPES
var HT_ITEMTYPE_TANK = '1';
var HT_ITEMTYPE_BODYBLANK = '2';
var HT_ITEMTYPE_RAWSTEEL = '3';
var HT_ITEMTYPE_HEAD = '4';
var HT_ITEMTYPE_BRACKET = '5';
var HT_ITEMTYPE_SKID = '14';

// HT PRINT MASS BOL PROCESSING STATUS
var HT_PRINTBOLSTATUS_OPEN = '1';
var HT_PRINTBOLSTATUS_QUEUED = '2';
var HT_PRINTBOLSTATUS_PROCESSING = '3';
var HT_PRINTBOLSTATUS_PROCESSING_COMPLETE = '4';

// HT PRICING UPDATE PROCESSING STATUSES
var HT_PRICINGUPDATE_STATUS_OPEN = '1';
var HT_PRICINGUPDATE_STATUS_PROCESSING = '2';
var HT_PRICINGUPDATE_STATUS_SENDEMAILS = '3';
var HT_PRICINGUPDATE_STATUS_PROCESSED = '4';

// PRE-PRO PROCESSING STATUSES
var HT_PREPROPROCESSING_STATUS_OPEN = '1';
var HT_PREPROPROCESSING_STATUS_RELEASINGPRODWO = '2';
var HT_PREPROPROCESSING_STATUS_DELETINGDEMANDWO = '3';
var HT_PREPROPROCESSING_STATUS_CHOOSEASSEMBLIES = '4';
var HT_PREPROPROCESSING_STATUS_CREATESCHEDULES = '5';
var HT_PREPROPROCESSING_STATUS_PLANNINGPRODWO = '6';
var HT_PREPROPROCESSING_STATUS_CREATINGDEMANDWO = '7';

// PRICE LEVELS
var HT_PRICELEVEL_CUSTOM = '-1';
var HT_PRICELEVEL_CURRENTBASE = '1';
var HT_PRICELEVEL_CURRENTPREFERRED = '2';
var HT_PRICELEVEL_CURRENTTOPLEVEL = '6';
var HT_PRICELEVEL_FUTUREBASE = '7';
var HT_PRICELEVEL_FUTUREPREFERRED = '8';
var HT_PRICELEVEL_FUTURETOPLEVEL = '9';

// ADMIN ROLE
var HT_ROLE_ADMIN = '3';

// Transaction line item types
var HT_TRANSACTIONLINE_ITEMTYPE_ASSEMBLY = 'Assembly';

//Custom List Series Type
var HT_SERIES_TYPE_STEEL = 1;
var HT_SERIES_TYPE_ALUM = 2;